#!/bin/bash

echo "Setting up homebrew-cask"
brew tap homebrew/cask

echo "install cmd applications"
brew install vim

echo "setup git"
echo ".idea" >> ~/.gitignore_global
git config --global core.excludesfile ~/.gitignore_global
git config --global user.name "James Armstead"
git config --global user.email james@basistheory.com

echo "install desktop applications"
brew install brave-browser --cask
brew install iterm2 --cask
brew install yarn --cask
brew install sizeup --cask
Brew install insomnia --cask
brew install slack --cask
brew install --cask visual-studio-code
brew install tweetbot --cask


echo "DONE -- run custom-zsh.sh to finish install"